# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7350cb31f3f832bc1d936a7dd86988437305184df4a1aa8cec6e5512b9600636e749bcd58bd9bc5e310492ffd8899ed5c965658bc4713f1b709fd327fa589775

test:
  secret_key_base: bd8fa75220120ba3d9d0b0bfe254acee0c65301ae6213a1a1dc1993f726547236c69342372a660c5f6e3e08d76cd140e1152777dc0672cd90bd9019d9a64b0ef

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
